export enum Signals {
    PlayerSpawn = 'playerSpawn',
    PlayerDeath = 'playerDeath',
    Pause = 'pause',
    Resume = 'resum',
    UpgradePlayer = 'upgrade_player',
    CloseMenu = 'close_menu',
    RoomConstruct = 'room_construct',
    RoomStart = 'room_start',
    AllEnemiesDefeated = 'all_enemies_defeated',
    RoomComplete = 'room_complete',
    RoomDestroy = 'room_destroy',
    DungeonConstruct = 'dungeon_construct',
    DungeonComplete = 'dungeon_complete',
}